# Generated by Django 5.0.7 on 2024-07-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='relacao',
            field=models.CharField(choices=[('velocidade', 'velocidade'), ('unica', 'unica')], max_length=250),
        ),
    ]
