# Generated by Django 5.0.7 on 2024-07-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_peca_relacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='imagem',
            field=models.ImageField(default=1, upload_to='media/imagem/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
