# Generated by Django 5.0.7 on 2024-07-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_peca_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='media/imagem/%Y/%m/%d/'),
        ),
    ]
