# Generated by Django 5.0.7 on 2024-07-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_peca_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
