# Generated by Django 5.0.7 on 2024-07-24 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_peca_publicada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peca',
            name='publicada',
        ),
    ]
