# Generated by Django 5.0.7 on 2024-08-04 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_remove_peca_publicada'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modadalidade',
            new_name='Modalidade',
        ),
    ]
